### PR TITLE
Add HA MySQL sample

### PR DESCRIPTION
**Pull request by alexander-demicev**
This PR starts adding of HA apps samples. This is a simple 2 pods HA deployments of MySQL, made using official k8s docs

### CODE REVIEW

**Comment by jwmatthews** [comment]
@jmontleon please take a look, do you have any suggestions of anything else we'd like for a mysql ha example to help tease out issues with migration?

**Comment by jwmatthews** [comment]
@rthallisey we are trying to create a good example of mysql ha to help us tease out issues as we migrate a stateful app from one cluster to another.

Please take a quick look over this example and share if you have any suggestions we should consider to improve.

Thank you :)

**Comment by rthallisey** [comment]
I think you're going to need 3 sql servers for HA.

In an ideal migration, you're looking at scenarios 1 & 2 & 3 from https://www.percona.com/blog/2014/09/01/galera-replication-how-to-recover-a-pxc-cluster/ .  You're tricky scenarios are 4-7.  I think those are the main issues you'll want to cover.

**Comment by alexander-demicev** [comment]
@rthallisey I increased number of replicas to 3, is there anything else needed?

**Pull request merged**
